[package]
name = "upim-note"
version = "0.1.0"
authors = ["Ryan Frame <code@ryanjframe.com>"]
license = "MPL-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
upim-core = { path = "../upim-core" }
