[package]
name = "upim-edit"
version = "0.1.0"
authors = ["Ryan Frame <code@ryanjframe.com>"]
edition = "2018"

[dependencies]
upim-core = { path = "../../upim-core" }
upim-note = { path = "../../upim-note" }
anyhow = "1.0.38"
rand = "0.8.3"
