[package]
name = "upim-edit"
version = "0.1.0"
authors = ["Ryan Frame <code@ryanjframe.com>"]
license = "MPL-2.0"
edition = "2018"

[dependencies]
upim-core = { path = "../../upim-core" }
upim-note = { path = "../../upim-note" }
anyhow = "1.0.38"

[dev-dependencies]
rand = "0.8.3"
