[package]
name = "upim-core"
version = "0.1.0"
authors = ["Ryan Frame <code@ryanjframe.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
